# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['TetrisRedux.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        '_asyncio',
        '_bz2',
        '_ctypes',
        '_decimal',
        '_elementtree',
        '_hashlib',
        '_lzma',
        '_multiprocessing',
        '_overlapped',
        '_queue',
        '_socket',
        '_ssl',
        '_wmi',
        'asyncio',
        'concurrent',
        'ctypes',
        'curses',
        'email',
        'html',
        'http',
        'json',
        'logging',
        'multiprocessing',
        'numpy',
        'numpy.libs',
        'OpenGL',
        'pkg_resources',
        'pydoc_data',
        'psutil',
        'unittest',
        'xml',
        'xmlrpc',
        'yaml'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TetrisRedux',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='file_version_info.txt',
    uac_admin=False,
    icon=['tetris.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TetrisRedux',
)
